config/routes.rb
Rails.application.routes.draw do
    root to: 'home#welcome'
    get '/welcome', to: 'home#welcome'
    get '/services', to: 'home#services'
    get '/interiors', to: 'home#interiors'
    get '/search', to: 'home#search'
    get '/kitchen', to: 'services#kitchen'
    get '/bathroom', to: 'services#bathroom'
    get '/bedroom', to: 'services#bedroom'
    get '/modern', to: 'interiors#modern'
    get '/contemporary', to: 'interiors#contemporary'
    get '/traditional', to: 'interiors#traditional'
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def welcome
    
  end

  def services

  end

  def interiors

  end

  def search
    case params[:option]
    when 'services' then redirect_to(services_path)
    when 'interiors' then redirect_to(interiors_path)
    when 'kitchen' then redirect_to(kitchen_path)
    when 'bathroom' then redirect_to(bathroom_path)
    when 'bedroom' then redirect_to(bedroom_path)
    when 'modern' then redirect_to(modern_path)
    when 'contemporary' then redirect_to(contemporary_path)
    when 'traditional' then redirect_to(traditional_path)
    else render :welcome
  end
end
end

app/controllers/interiors_controller.rb
class InteriorController < ApplicationController

  def modern

  end

  def contemporary

  end

  def traditional

  end

end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def kitchen

  end

  def bathroom

  end

  def bedroom

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/welcome.html.erb
<h1>Welcome to Home Adore Interior Design Services</h1>

<%= form_tag(search_path, method: :get) do %>
<p>Enter a search term below</p>
<%= text_field_tag :option %>
<%= submit_tag "Search" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HomeAdoreApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<nav>
  <ul>
    <li><%= link_to "home", root_path %></li>
    <li><%= link_to "services", services_path %></li>
    <li><%= link_to "interiors", interiors_path %></li>
  
  </ul>
</nav>

<body>


<%= yield %>

</body>
</html>

app/views/services/kitchen.html.erb
hello